save_profile:
  name: Save profile
  description: Saves the current settings into a named profile
  fields:
    name:
      name: Profile name
      description: Name of the profile to save (e.g. School, Holidays)
      required: true
      selector:
        text:
    entry_id:
      name: Entry ID
      description: Config entry ID (optional if only one device is configured)
      required: false
      selector:
        text:

delete_profile:
  name: Delete profile
  description: Deletes a user profile
  fields:
    name:
      name: Profile name
      description: Name of the profile to delete
      required: true
      selector:
        text:
    entry_id:
      name: Entry ID
      description: Config entry ID (optional if only one device is configured)
      required: false
      selector:
        text:
